apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: config-service
  name: config-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: config-service
    spec:
      containers:
      - image: saboor922/config-service:latest
        name: config-service
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}
