apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: random-service
  name: random-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: random-service
    spec:
      containers:
      - env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://discovery-service:9001/eureka
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-service:9000
        image: saboor922/random-service:latest
        name: random-rest-service
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
