apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: vehicle-mongodb
  name: vehicle-mongodb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: vehicle-mongodb
    spec:
      containers:
      - env:
        - name: MONGO_DATA_DIR
          value: /data/db
        - name: MONGO_LOG_DIR
          value: /dev/null
        image: saboor922/vehicle-mongodb:latest
        name: vehicle-mongodb
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
