version: "3"
services:
  config-service:
    container_name: config-service
    build:
      context: .
      dockerfile: ./configService/Dockerfile
    image: saboor922/config-service:latest
    expose:
      - 9000
    ports:
      - 9000:9000
    networks:
      - docker_network
  discovery-service:
    container_name: discovery-service
    build:
      context: .
      dockerfile: ./discoveryService/Dockerfile
    image: saboor922/discovery-service:latest
    expose:
      - 9001
    ports:
      - 9001:9001
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:9000
    networks:
      - docker_network
  random-service:
    container_name: random-rest-service
    build:
      context: .
      dockerfile: ./randomRestService/Dockerfile
    image: saboor922/random-service:latest
    expose:
      - 8081
    ports:
      - 8081:8081
    logging:
      driver: json-file
    depends_on:
      - config-service
      - discovery-service
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:9000
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:9001/eureka
    networks:
      - docker_network
  vehicle-service:
    container_name: vehicle-service
    build:
      context: .
      dockerfile: ./vehicleService/Dockerfile
    image: saboor922/vehicle-service:latest
    expose:
      - 8082
    ports:
      - 8082:8082
    depends_on:
      - config-service
      - discovery-service
      - vehicle-mongodb
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:9000
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:9001/eureka
    logging:
      driver: json-file
    networks:
      - docker_network
  vehicle-mongodb:
    container_name: vehicle-mongodb
    image: saboor922/vehicle-mongodb:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    expose:
      - 27017
    ports:
      - 27017:27017
    logging:
      driver: json-file
    networks:
      docker_network:
        aliases:
          - "vehicle-mongodb"
networks:
  docker_network:
    driver: bridge
